# Generated by Django 2.2.10 on 2020-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=5000)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
