# Generated by Django 2.2.10 on 2020-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateField(),
        ),
    ]
